### ISSUE TITLE
Add #![feature(alloc)], when enabling collections and/or alloc feature

### ISSUE THREAD

**Issue by MathiasKoch** [jethrogb/rust-core_io#20]
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/mathias/.cargo/registry/src/github.com-1ecc6299db9ec823/core_io-0.1.20190427/src/lib.rs:15:51
   |
15 | #[cfg(all(feature="collections",no_collections))] extern crate alloc as collections;
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(alloc)] to the crate attributes to enable

**Comment by jethrogb** [comment]
Whoops, looks like this was accidentally broken in 81adf070b3a5730160d7428c05c1bc73c1eca509

**Comment by jethrogb** [comment]
All these features need to be added back:

* alloc
* collections
* str_char
* unicode

@parasyte do you think you'd be able to fix this and #19?

**Comment by parasyte** [comment]
I wasn't able to build with those features enabled. :( `rustc` complained that they were unknown.

**Comment by jethrogb** [comment]
That's weird, the crate has `#![allow(stable_features,unused_features)]`

**Comment by parasyte** [comment]
I'll look at it when I get time this week.

**Comment by jethrogb** [comment]
Hmm I just tried it on nightly and indeed I can't use collections, str_char, unicode (alloc works though)

**Comment by jethrogb** [comment]
Behavior changed between:
* nightly-2018-08-06 73c78734b
* nightly-2018-08-14 d5a448b3f

**Comment by jethrogb** [comment]
Introduced in https://github.com/rust-lang/rust/pull/52644

**Comment by jethrogb** [comment]
I guess we'll need to use the same version detection mechanism already in use for other features: https://github.com/jethrogb/rust-core_io/blob/master/build.rs#L52-L64

**Comment by parasyte** [comment]
Cool! I didn't even know that existed. Sounds good, I should be able to bisect where all of the features needed changes. (I had to add/remove features about 3 different times IIRC)

**Comment by MathiasKoch** [comment]
Any progress on this?

**Comment by parasyte** [comment]
I started on this. It's going to take some time because I need to rebuild the patches.
